### ISSUE TITLE
Error by downloading large file

### ISSUE THREAD

**Issue by WenjieYan** [tychxn/baidu-wangpan-parse#10]
Hi, 

I am trying downloading a large file from Baidu. After running your script, I got a link succesfully, however, when I use this link I got an error 

{"error_code":31090,"error_msg":"package is too large","request_id":569963062413958513}

Could you have a look on this issue? Thanks

WY

C:\Users\alex1\Downloads\baidu-wangpan-parse-master\baidu-wangpan-parse-master>python baidu_wangpan_parse.py -f https://pan.baidu.com/s/1kWsBk4hME_vMo-2huAPJ-A  1z5l

http://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%2239961410290532%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:7%2BP4E1tqxc8ELcaBRx5wwb3pfT4%3D&uid=3050104991&time=1538420514&dp-logid=569963062413958513&dp-callid=0&shareid=699190672&from_uk=3050104991

**Comment by tychxn** [comment]
Hi,

I have tested this issue using some chrome extensions, but get the same error. So I guess it's limited by Baidu server when you download too large package, and there is no solution so far.
If you have any idea to break the restriction, please let me know.

Tychxn.
