### ISSUE TITLE
验证码会在什么情况下出现

### ISSUE THREAD

**Issue by I-love-study** [tychxn/baidu-wangpan-parse#3]
本人想通过QQ做一个远程下载服务器
但是验证码的问题就很烦(QQ网页版传不了图片)
所以想问这个问题

**Comment by tychxn** [comment]
- 当一段时间内请求过于频繁的时候就会出现验证码，你可以不停地运行几次脚本应该就会出现。
- 验证码图片的```url="http://pan.baidu.com/genimage?%s" % self.verifyCodeStr```，你可以返回验证码图片链接，在本地查看。
