### ISSUE TITLE
请教一下为什么不把目录里面的内容的下载链接做成一个列表返回呢

### ISSUE THREAD

**Issue by chinaids** [tychxn/baidu-wangpan-parse#4]

**Comment by tychxn** [comment]
因为这样需要对目录中的每个文件都解析下载链接，当时没有分析相关的接口，为了省事，就直接把整个文件夹打包下载了。

**Comment by chinaids** [comment]
还有一个问题想请教一下，代码里面用到的http接口是有官方文档还是自己抓包分析的呢，我现在有个需求想要对某个目录下的文件进行逐个后去下载链接，能请分享一下这些http接口的文档吗？

**Comment by tychxn** [comment]
百度是不会给你提供接口和文档让你调用的，只能通过多次抓包分析，比较不同之处，然后构造自己的请求。建议使用fiddler分析数据包~
