### ISSUE TITLE
新功能申请（删除文件）

### ISSUE THREAD

**Issue by zlccgfkd** [tychxn/baidu-wangpan-parse#5]
请教一下，我想通过抓包发现的
https://pan.baidu.com/api/filemanager
接口来封装一个删除百度网盘文件的api接口，但即使我构造了跟浏览器一模一样的请求头和cookie等信息，仍然会报错（Google得知为参数错误），请问您有没有什么指导意见？期待您的回复

**Comment by tychxn** [comment]
这个可能得周末我才有空看一下，因为我自己也没有用百度网盘存放文件。
如果可以的话把你的请求数据包贴上来看一下吧。

**Comment by zlccgfkd** [comment]
[https://www.cnblogs.com/countryKing/p/9495886.html](url)
因此处编辑不便，我将详细内容写在博客中，还清您移步上列链接查看细致内容
本人邮箱：zlccgfkd@outlook.com
期待您的回复，谢谢

**Comment by tychxn** [comment]
代码第72行
```diff
- "filelist" : ["/test.jpg"]
+ "filelist" : '["/test.jpg"]'
```
Have fun~

**Comment by zlccgfkd** [comment]
哇，成功啦，非常感谢您的无私帮助，已在博客中向您致谢

**Comment by tychxn** [comment]
哈哈，不客气~
